# Generated by Django 3.2.6 on 2021-08-05 13:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_title', models.CharField(default=None, max_length=50)),
                ('donation_amount', models.CharField(default=None, max_length=70)),
                ('description', models.TextField(default=None)),
                ('donation_time', models.DateTimeField(default=datetime.datetime(2021, 8, 5, 13, 9, 22, 563152, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(default=None, max_length=50)),
                ('project_name', models.CharField(default=None, max_length=50)),
                ('description', models.TextField(default=None)),
                ('amount', models.CharField(default=None, max_length=70)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donor.category')),
            ],
        ),
    ]
