# Generated by Django 3.2.6 on 2021-08-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(default=None, max_length=50)),
                ('project_name', models.CharField(default=None, max_length=50)),
                ('description', models.TextField(default=None)),
                ('amount', models.CharField(default=None, max_length=70)),
            ],
        ),
    ]
