# Generated by Django 3.2.6 on 2021-08-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationrequest',
            old_name='categories',
            new_name='category',
        ),
    ]
