# Generated by Django 3.2.6 on 2021-08-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0002_rename_categories_donationrequest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='category',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
