# Generated by Django 3.2.6 on 2021-08-05 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0003_auto_20210805_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donor.category'),
        ),
    ]
