# Generated by Django 3.2.6 on 2021-08-05 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Donor', '0004_auto_20210805_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_title', models.CharField(default=None, max_length=50)),
                ('donation_amount', models.CharField(default=None, max_length=70)),
                ('description', models.TextField(default=None)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('donor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
