# Generated by Django 3.2.6 on 2021-08-05 10:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0005_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donation_date',
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 10, 21, 50, 936765, tzinfo=utc)),
        ),
    ]
