# Generated by Django 3.2.6 on 2021-08-05 10:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Donor', '0007_alter_donation_donation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 10, 24, 53, 442889, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
