# Generated by Django 3.2.6 on 2021-08-04 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('pitch', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('amount_needed', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('past_projects', models.TextField()),
                ('funded', models.BooleanField(default=False, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.category')),
            ],
        ),
    ]
