# Generated by Django 3.2.6 on 2021-08-14 18:48

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['-donation_time']},
        ),
        migrations.AlterModelOptions(
            name='ngo',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='ngo',
            old_name='categorys',
            new_name='categories',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='summary',
        ),
        migrations.AddField(
            model_name='ngo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ngo',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ngo.ngoprofile'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donation_amount',
            field=models.IntegerField(default=0, max_length=70),
        ),
        migrations.AlterField(
            model_name='donor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ngo.donorprofile'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Profilepics/'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ngoprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Profilepics/'),
        ),
    ]
